DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user (id INTEGER PRIMARY KEY, email TEXT, username TEXT, passkey TEXT, created_at DATE);

DROP TABLE IF EXISTS workspace;
CREATE TABLE IF NOT EXISTS workspace (id INTEGER PRIMARY KEY, title TEXT, created_at DATE);

DROP TABLE IF EXISTS project;
CREATE TABLE IF NOT EXISTS project (id INTEGER PRIMARY KEY, title TEXT, workspace_id INTEGER, FOREIGN KEY(workspace_id) REFERENCES workspace(id) ON DELETE CASCADE);

DROP TABLE IF EXISTS task;
CREATE TABLE IF NOT EXISTS task (id INTEGER PRIMARY KEY, title TEXT);

DROP TABLE IF EXISTS workspace_admin;
CREATE TABLE IF NOT EXISTS workspace_admin (id INTEGER PRIMARY KEY, user_id INTEGER, workspace_id INTEGER, FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE, FOREIGN KEY(workspace_id) REFERENCES workspace(id) ON DELETE CASCADE);

DROP TABLE IF EXISTS workspace_member;
CREATE TABLE IF NOT EXISTS workspace_member (id INTEGER PRIMARY KEY, user_id INTEGER, workspace_id INTEGER, FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE, FOREIGN KEY(workspace_id) REFERENCES workspace(id) ON DELETE CASCADE);

DROP TABLE IF EXISTS project_member;
CREATE TABLE IF NOT EXISTS project_member (id INTEGER PRIMARY KEY, project_id INTEGER, member_id INTEGER, FOREIGN KEY(project_id) REFERENCES project(id) ON DELETE CASCADE, FOREIGN KEY(member_id) REFERENCES workspace_member(id) ON DELETE CASCADE);